### PR TITLE
Add Batch write to write to DB. Add Custom Field to DB

### PR DESCRIPTION
**Pull request by winstontj**
- Add Batch Write with interval to reduce db process
- disable function when error connecting to db
- Add custom metaData field to DB
- Prevent infinite loop when error occurred on this module

### CODE REVIEW

**Comment by richardgarnier** [comment]
Same problem with the var declarations

**Comment by richardgarnier** [comment]
typo on isnertedLogData -> insertedLogData

**Comment by richardgarnier** [comment]
If insert is called during the execution of collection.insert, (before the callback is called), don't we risk to lose some logs? Since the reference to the array is shared.

**Comment by winstontj** [comment]
Yes it is. Thanks for pointing that out. We might lose some data when it happens. 
I'll copy the data and work on the copied version then.

**Comment by richardgarnier** [comment]
You can just swap the reference instead of copying the entire array.
```
function batchInsert() {
         var options = getOptions();
         var insertedBatchLog;
         // console.debug('Do Batch insert Total log ' + batchLogEvent.length);
         // Only insert log if there are event to be logged
         if (batchLogEvent.length > 0) {
             // Clear the batch log and copy all of it's data to new array.
             // This is done to prevent new data being deleted when the insert function is running
             insertedBatchLog = batchLogEvent;
             batchLogEvent = [];
             if (collection) {
                 // Always write with safe option
                 collection.insert(insertedBatchLog, options, function (error) {
                     if (error) {
                         // log4js.error('log: Error writing data to log!');
                         logger.error(error);
                         // log4js.error('log: Connection: %s, collection: %, data: %j', config.connectionString, collectionName, loggingEvent);
                     }
                 });
             } else {
                 cache.push(insertedBatchLog);
             }
         }
     }
```

**Comment by winstontj** [comment]
Thanks for pointing that out. I've removed the splice and just do array switching.

**Pull request merged**
